[RFC] Multiple Recaptcha Forms on Page Fix | Issue #85
bobdenotter/forms pull request #87
Opened 2021-11-17 12:48 UTC by sJones1997

Have added in a fix that converts the form name from snake case to camel case and concats the camel case name to both the onRecaptchaSubmit function and to the data-callback attribute.

2021-11-26 12:06 UTC, sJones1997 commented
@bobdenotter just wondering if you've seen?

2021-12-21 11:23 UTC, I-Valchev requested changes

2021-12-21 11:23 UTC, I-Valchev commented on src/FormBuilder.php
> +                // $attr = [
Hi @sJones1997 , sorry for the late response on this!

It looks good, can you remove those commented out lines? I can merge it in and tag a release then.

2021-12-21 13:28 UTC, bobdenotter commented
Hi @sJones1997,

Sorry, I completely missed this. I took the liberty of ninja-editing out the commented code, so we can merge it in! 

Thanks! 👍

2021-12-21 13:28 UTC, merged